version: "3"
networks:
    cuams_bot:
        external: true
services:
    cuams_bot_node:
        container_name: cuams_bot_node_staging
        build: ./application
        networks:
            cuams_bot:
                aliases:
                 - node
        volumes:
            - /var/jenkins_home/credentials_staging:/app/credentials
        ports:
            - "9012:9012"